---
- name: installing {{ iperf_eff_name }} os package...
  become: true
  become_user: root
  package:
    name: '{{ iperf_eff_name }}'
    state: present
- name: installing systemd service unit
  when: iperf_systemd_install
  include_tasks: systemd.yml
