---
- name: Installing {{ iperf_eff_name }} os package...
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ iperf_eff_name }}'
    state: present
- name: Installing systemd service unit
  when: iperf_systemd_install
  ansible.builtin.include_tasks: systemd.yml
