---
- name: Adding {{ iperf_eff_name }} user...
  become: true
  become_user: root
  ansible.builtin.user:
    name: '{{ iperf_eff_name }}'
    shell: /sbin/nologin

- name: Installing {{ iperf_eff_name }}.service systemd unit...
  become: true
  become_user: root
  ansible.builtin.template:
    src: iperf.service.j2
    dest: /etc/systemd/system/{{ iperf_eff_name }}.service
    mode: '644'

- name: Launching {{ iperf_eff_name }} service...
  become: true
  become_user: root
  ansible.builtin.service:
    name: '{{ iperf_eff_name }}'
    state: '{{ iperf_systemd_state }}'
    enabled: '{{ iperf_systemd_enabled }}'
